# Generated by Django 4.2.13 on 2024-06-28 08:30

import functools

from django.db import migrations, models

import apps.common.services


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="XSDSchema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "xsd_schema",
                    models.FileField(
                        upload_to=functools.partial(
                            apps.common.services.upload_file_handler_path,
                            *("files/xml_transit/xsd_schemas",),
                            **{}
                        ),
                        verbose_name="xsd schema",
                    ),
                ),
                ("folder_name", models.CharField(max_length=100, verbose_name="folder name")),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "individual entrepreneur"), (1, "legal entity")],
                        verbose_name="type",
                    ),
                ),
            ],
            options={
                "verbose_name": "xsd schema",
                "verbose_name_plural": "xsd schemas",
            },
        ),
    ]
