[base]
secret_key = "django-insecure-%hj36iymd#14dio6qylhc+mhzhf=p33_(-(*r+ll_j)@e^e9oz"
debug = false

[storage]
media_url = "/media/"
media_root = "media/"
static_url = "/static/"
secure_links_secret = "insecure-mkjnhygtfdhgvjbknli"

[celery]
broker_url = "redis://localhost:6379/2"
task_time_limit = 3600
visibility_timeout = 3600
polling_interval = 1

[ftp]
host = ""
cert = ""
pass = ""
